GalleryBundle\Entity\File:
    type: entity
    # Many Files for One Team
    manyToOne:
        team:
            targetEntity: AccountBundle\Entity\Team
            joinColumn:
                name: team_id
                referencedColumnName: id
                onDelete: CASCADE
    table: null
    repositoryClass: GalleryBundle\Repository\FileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '65'
        type:
            type: string
            length: '45'
        alt:
            type: string
            length: '128'
            nullable: true
        uploadDate:
            type: datetime
        files:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
