PlanningBundle\Entity\Matchs:
    type: entity
    # Many Matches in one Place (ManyToOne)
    manyToOne:
        place:
            targetEntity: Place
            joinColumn: 
                name: place_id
                referencedColumnName: id
    # Many Match played by One Team
    # manyToOne:
        team:
            targetEntity: AccountBundle\Entity\Team
            inversedBy: Match
            joinColumn:
                name: team_id
                referencedColumnName: id
                onDelete: CASCADE
        team2:
            targetEntity: AccountBundle\Entity\Team
            joinColumn:
                name: team2_id
                referencedColumnName: id
                onDelete: CASCADE
                       
    table: null
    repositoryClass: PlanningBundle\Repository\MatchsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateMatch:
            type: datetime
        domicile:
            type: boolean
    lifecycleCallbacks: {  }
