PlanningBundle\Entity\Place:
    type: entity
    # One place have One room manager (OneToOne)
    #oneToOne:
    #    roomManager:
    #        targetEntity: AccountBundle\Entity\Person
    #        joinColumn:
    #            name: roommanager_id
    #            referencedColumnName: id
    #            onDelete: CASCADE
    table: null
    repositoryClass: PlanningBundle\Repository\PlaceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        room:
            type: string
            length: 255
        city:
            type: string
            length: '128'
    lifecycleCallbacks: {  }
