planning:
    resource: "@PlanningBundle/Resources/config/routing.yml"
    prefix:   /

gallery:
    resource: "@GalleryBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"

