account:
    resource: "@AccountBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"

planning:
    resource: "@PlanningBundle/Resources/config/routing.yml"
    prefix:   /planning

gallery:
    resource: "@GalleryBundle/Resources/config/routing.yml"
    prefix:   /gallery



