app:
    resource: "@AppBundle/Resources/config/routing.yml"

account:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

planning:
    resource: "@AppBundle/Resources/config/routing/plannings/plannings.yml"
    prefix:   /planning

gallery:
    resource: "@GalleryBundle/Resources/config/routing.yml"
    prefix:   /gallery