# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user@gmail.com:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin@mail.ru:
                        password: kitten
                        roles: 'ROLE_ADMIN'

    encoders:
         Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:    ROLE_USER
        ROLE_MANAGER: [ROLE_MANAGER, ROLE_USER]
        ROLE_ADMIN:   [ROLE_USER, ROLE_MANAGER, ROLE_ADMIN]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            form_login:
                login_path: app_login
                check_path: app_login

            # Active le logout (ne fonctionne pas avec http_basic)
            logout:
                path:   /logout
                target: app_login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        # le panneau d'admin est réservé au superadmin (crud, attribution des droits)
        # mais il y a un role pour la gestion des plannings (ROLE_MANAGER, crud plannings, events...) 
        # access control a gérer par la suite (voir le routage)