# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_user_provider:
            entity:
                class: AccountBundle:Person
                property: email

    encoders:
          AccountBundle\Entity\Person:
              algorithm: bcrypt
              cost: 12

    role_hierarchy:
        ROLE_USER:    ROLE_USER
        ROLE_MANAGER: [ROLE_MANAGER, ROLE_USER]
        ROLE_ADMIN:   [ROLE_USER, ROLE_MANAGER, ROLE_ADMIN]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: our_user_provider
            # activate different ways to authenticate

            form_login:
                login_path: app_login
                check_path: app_login

            # Active le logout (ne fonctionne pas avec http_basic)
            logout:
                path:   /logout
                target: app_login

    access_denied_url: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/teams/\d/gallery, roles: ROLE_USER }
        - { path: ^/teams/\d/show, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/m, roles: ROLE_MANAGER }
        # le panneau d'admin est réservé au superadmin (crud, attribution des droits)
        # mais il y a un role pour la gestion des plannings (ROLE_MANAGER, crud plannings, events...) 
        # access control a gérer par la suite (voir le routage)