app_teams_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:teams }

app_teams_show:
    path: /{id}/show
    defaults: { _controller: AppBundle:Default:teamsShow }

#app_teams_details:
#    path: /{id}
#    defaults: { _controller: AccountBundle:Team:teamMembers}

app_teams_gallery:
    path: /{id}/gallery
    defaults: { _controller: AppBundle:Default:teamsGallery }

app_teams_category:
    resource: "@AppBundle/Resources/config/routing/appli/teams/category.yml"
    prefix:   /category