AccountBundle\Entity\Role:
    type: entity
    # Many roles in One Club (asptt) (ManyToOne)
    manyToOne:
        club:
            targetEntity: AppBundle\Entity\Club
            joinColumn:
                name: club_id
                referencedColumnName: id
                onDelete: CASCADE
    table: null
    repositoryClass: AccountBundle\Repository\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roleName:
            type: string
            length: '64'
            unique: true
        roleRights:
            type: string
            unique: false
    lifecycleCallbacks: {  }
