AccountBundle\Entity\Team:
    type: entity
    # Many Categories for one Team (ManyToOne)
    manyToOne:
        category:
            targetEntity: Category
            joinColumn:
                name: category_id
                referencedColumnName: id
    # One Team belongs to One Club (OneToOne)
    oneToOne:
        club:
            targetEntity: AppBundle\Entity\Club
            joinColumn:
                name: club_id
                referencedColumnName: id
    table: null
    repositoryClass: AccountBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '64'
            unique: true
        resumptionDate:
            type: datetime
            nullable: true
        trainingDay:
            type: string
            length: '16'
            nullable: true
        trainingTime:
            type: string
            length: '16'
            nullable: true
    lifecycleCallbacks: {  }
