AccountBundle\Entity\Team:
    type: entity
    # Many Teams for one Category (ManyToOne)
    manyToOne:
        category:
            targetEntity: Category
            joinColumn:
                name: category_id
                referencedColumnName: id
                onDelete: CASCADE
            # oneToMany:
        matchs:
            targetEntity: PlanningBundle\Entity\Matchs
            mappedBy: team
            joinColumn:
                onDelete: CASCADE
    # Many teams belongs to One coach (Person) (ManyToOne)
        coach:
            targetEntity: AccountBundle\Entity\Person
            mappedBy: person
            joinColumn:
                name: coach_id
                referencedColumnName: id
                onDelete: CASCADE
    # One Team belongs to One Club (OneToOne)
        club:
            targetEntity: AppBundle\Entity\Club
            mappedBy: club
            joinColumn:
                name: club_id
                referencedColumnName: id
                onDelete: CASCADE
    table: null
    repositoryClass: AccountBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '64'
            unique: true
        resumptionDate:
            type: datetime
            nullable: true
        trainingDay:
            type: string
            length: '16'
            nullable: true
        trainingTime:
            type: string
            length: '16'
            nullable: true
    lifecycleCallbacks: {  }