role_index:
    path:     /
    defaults: { _controller: "AccountBundle:Role:index" }
    methods:  GET

role_new:
    path:     /new
    defaults: { _controller: "AccountBundle:Role:new" }
    methods:  [GET, POST]

role_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountBundle:Role:edit" }
    methods:  [GET, POST]

role_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountBundle:Role:delete" }

role_show:
    path:     /{id}/show
    defaults: { _controller: "AccountBundle:Role:show" }
    methods:  GET

role_person:
    resource: "@AppBundle/Resources/config/routing/admin/role/person.yml"
    prefix:   /{id}/person