# Routing.yml
#
# Fichier de Routing principal du site
# (Tous les CRUDS sont redirigés vers /admin)

#Partie Security
app_login:
    path: /login
    defaults: { _controller: AccountBundle:Security:login }

app_logout:
    path: /logout

app_register:
    path: /register
    defaults: { _controller: AccountBundle:Security:register }

# Partie publique avec path direct :
app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_apropos:
    path: /a-propos
    defaults: { _controller: AppBundle:Default:apropos }

app_contact:
    path: /contact
    defaults: {  _controller: AppBundle:Default:contact  }

app_inscription:
    path: /inscription
    defaults: { _controller: AppBundle:Default:inscription }

app_search:
    path: /search
    defaults: { _controller: AppBundle:Default:search }

# Partie Appli
app_plannings:
    resource: routing/appli/plannings.yml
    prefix: /plannings

app_teams:
    resource: routing/appli/teams.yml
    prefix: /teams

app_user:
    resource: routing/appli/user.yml
    prefix: /user

app_event:
    resource: routing/appli/event.yml
    prefix: /event

app_match:
    resource: routing/appli/match.yml
    prefix: /match

app_category:
    resource: routing/appli/category.yml
    prefix: /category

# Partie Admin:
app_admin:
    resource: "@AppBundle/Resources/config/routing/admin/admin.yml"
    prefix:   /admin

app_manager:
    resource: "@AppBundle/Resources/config/routing/manager/manager.yml"
    prefix: /m