# Routing.yml
#
# Fichier de Routing principal du site
# (Tous les CRUDS sont redirigés vers /admin)

# Partie publique :

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_apropos:
    path: /a-propos
    defaults: { _controller: AppBundle:Default:apropos }

app_contact:
    path: /contact
    defaults: {  _controller: AppBundle:Default:contact  }

app_inscription:
    path: /inscription
    defaults: { _controller: AppBundle:Default:inscription }

app_plannings:
    resource: routing/plannings/plannings.yml

app_teams:
    resource: routing/teams/teams.yml

app_login:
    path: /login
    defaults: { _controller: AccountBundle:Security:login }

app_logout:
    path: /logout

app_register:
    path: /register
    defaults: { _controller: AccountBundle:Security:register }

app_profile:
    path: /{id}
    defaults: { _controller: AccountBundle:Person:profile }
    methods:  GET

app_search:
    path: /search
    defaults: { _controller: AppBundle:Default:search }

# Partie Admin:

app_admin:
    resource: "@AppBundle/Resources/config/routing/admin/admin.yml"
    prefix:   /admin

app_manager:
    resource: "@AppBundle/Resources/config/routing/manager/manager.yml"
    prefix: /m