AppBundle\Entity\Club:
    type: entity
    # Many Events for one Club (ManyToOne)
    manyToOne:
        event:
            targetEntity: Event
            joinColumn:
                name: event_id
                referencedColumnName: id
    table: null
    repositoryClass: AppBundle\Repository\ClubRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        history:
            type: text
            nullable: true
        clubValues:
            type: text
            nullable: true
    lifecycleCallbacks: {  }