AppBundle\Entity\Event:
    type: entity
    # Many Events for one Club (ManyToOne)
    manyToOne:
        club:
            targetEntity: Club
            joinColumn:
                name: club_id
                referencedColumnName: id
    table: null
    repositoryClass: AppBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        dateEvent:
            type: datetime
        description:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
